<p><strong>DANCING with the MASAI</strong></p>
<p><em>Our visit to Nairobi...by Gail Brighton&nbsp;</em></p>
<p>As we stepped off of the plane we were greeted by the warm sunshine of the Kenyan skies. We took a deep breath and prepared ourselves for a week long adventure in the city of Nairobi. As we scanned our immediate view, a virtual army of airport porters were lined up to take care of our needs, or so we thought.</p>
<p>As we approached these tall, athletic young fellows, they suddenly broke rank and each one virtually swarmed a visitor. One fellow grabbed my husband&rsquo;s luggage and fled to the left. Another took possession of my luggage and ran to the right. We stood for a moment in shock unprepared for the &lsquo;greeting&rsquo;. Once composed we began a chase of our property. For a moment we were totally apart in our quests!</p>
<p>With sign language and some pleading looks, we were able to retrieve our bags. It was time to pause and secure a referred taxi service, and so we did. An hour later we arrived at our reserved destination accommodation. It was a large wooden plantation style guest house, complete with a vast open veranda full of guests sipping tea and munching on cream cakes. The scene restored our faith in choosing Nairobi as a holiday adventure. After receiving a gracious welcome, the delicious meal, and meeting a few of the guests, the hours of flying took their toll on our bodies and we slipped away to catch some needed sleep.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
<p>As dawn broke we were awoken to breakfast in bed; a delicious feast of fruits, some familiar and some unknown, and tasty Kenyan coffee. Our day was off to a good start, and so was my husband Hap. He was off to check in at The Conference of World Health which would occupy his time for the next five days. The evenings were carefully scheduled with numerous social events for the attendees and their guests.&nbsp;</p>
<p>I, on the other hand, had a day totally free, and more to come. I set off that first morning full of enthusiasm to explore Nairobi. Totally unfamiliar as to exactly where I was, I paused and chose a landmark to make sure I got back to our lodgings later in the day. A tall structure reminding me of an English Folly stood out well on the landscape.</p>
<p>As my wander began, I found an abundance of produce markets which were particularly interesting in their varieties of products, many unknown to me. Vendors were wonderful to chat to and explain their wares. In outdoor spaces tables were filled with arts and crafts mainly brought to town by the peoples of the Masai Tribe. Beautiful handcrafted bead works, animal prints and colorful fabrics, carved wooden wares; masks, statues, kitchen bowls. All the vendors were friendly and informative about their items. Never did anyone try to talk me into purchasing, which was a welcome relief. I was quietly learning more and more about an exciting culture, without a worry about my safety. As the sun left the mid-sky I made my way back to my 'chosen landmark' and the peace of our guest house.</p>
<img src="/assets/uploads/fb82fed4dc4fb7f172b87f43117ee0ab/320dd56bf5f283f47faf5f15851e111c.png" alt="" />
<p>The days in Nairobi quickly slipped by as Hap enjoyed his conference, and I kept my routine of learning and exploring. In the evenings we met at the organized social events with other delegates and swapped stories of the day&rsquo;s adventures while eating sumptuous meals.</p>
<p>Months before, when Hap had enrolled for the conference, we were given the option of an extra day of touring. We signed on to visit a Masai Village, experience their life, and have the services of an English speaking guide. The last day arrived all too soon as we set off early in the morning with our driver in a rather beat up, aged, open-air Land Rover. We learned we were the only delegates who had chosen to take on the adventure which was fortunate for us.</p>
<p>Our host took it upon himself to make sure we saw everything on the distant drive over sand and dirt roads: Every animal you associate with Africa, many trees and desert flowers, and an unforgettable treasure of people walking into the city with their wares to sell or trade at the markets. Within a few hours we arrived at our destination, an inhabited and lively Masai Village. Children were everywhere playing or helping with chores of everyday living. We visited inside the homes constructed by the women and made of twigs, mud, urine and dried cow dung. We marveled at the efficiency of an open fire in the center of the structure vented through an open gap in the ceiling. We met the elders who governed the village. Listening intently, we heard from the guide of the bravery of the males protecting their families and herds of livestock, and constantly roaming the area for &lsquo;greener pastures&rsquo;. A nomadic quest.</p>
<p>As I have said, our guide was attentive, considerate and knowledgeable. He was a little boastful when he informed the group Hap was a medical doctor in Canada. As this information passed through the group the mood suddenly took a change. An elder stepped forward and taking Hap by the arm he whisked him away to another larger building. I was left in awe with an uneasy feeling until our guide informed me he had been taken to meet the village witch doctor, or medicine man. Their visit seemed to be never ending as the guide and I chatted and commented that all the males in the compound had disappeared.</p>
<p>Hap eventually reappeared and he was being regally followed by all the males in the Masai Village. They had red cloth draped over their bodies, necks and arms were bedecked with colorful beaded pieces such as I had seen in town, and each carried a tall, tapered wooden staff. I clutched my guides arm whispering "What&rsquo;s happening?"</p>
<p>His reply: "They have been told to dance for you". The next scene was simply magical. Arms were united in the air. Feet were up and down moving at a rapid pace. We were brought into the dance. We were pushed out of the dance. The final dance was fast, strong, almost war like, you could feel animosity. The dancers seemed momentarily in a trance, splitting only to grasp our hands making us spin wildly in a circle. As quickly as it started, it was over.</p>
<p>An elder moved to the center of the group to say farewell and beckoned Hap to join him and presented gifts from the medicine man; a crudely carved statue of himself and a copy of his healing &lsquo;broom wand&rsquo; complete with bead work and goat&rsquo;s hair bristles. Hap appeared overcome with the honor.</p>
<img src="/assets/uploads/fb82fed4dc4fb7f172b87f43117ee0ab/ba0a270f5d711884f53b60b0515a44f8.png" alt="" width="201" height="268" />
<img src="/assets/uploads/fb82fed4dc4fb7f172b87f43117ee0ab/75f6b88dd1c64702ab3269464bd9e949.png" alt="" width="201" height="274" />
<p style="text-align: center;">As evening set, we were bouncing&nbsp;&nbsp; along the road towards our 'home' in Nairobi. Our guide and I were idly chatting about the wonderful day. I innocently asked about the almost &lsquo;war-like&rsquo; segment of the dance.</p>
<p style="text-align: center;">The guided smiled asking if I was sure I wanted to know. As I nodded yes, he became serious and said; "That is a traditional Masai Performance depicting the animosity the tribe feels about the white man&rsquo;s interference with their way of life."</p>
<p style="text-align: center;">With those words, I maybe understood why no other delegates from our group had joined our excursion.</p>
<p style="text-align: center;">Perhaps they knew!</p>